// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerSourceAntivirus.Infrastructure.Persistence;

#nullable disable

namespace PerSourceAntivirus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260617202347_RansomwareProtection")]
    partial class RansomwareProtection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.DnsQueryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspicionReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DnsQueryEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.FileMetadataAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anomalies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DocumentCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DocumentModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasEmbeddedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasJavaScript")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPolyglot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("FileMetadataResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HashReputationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMalicious")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositiveDetections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEngines")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("HashReputationResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HoneypotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecoyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TouchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasTouched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HoneypotFiles");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.MbrSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DriveIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectorSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriveIndex", "IsBaseline");

                    b.ToTable("MbrSnapshots");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.NetworkConnectionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlocklistReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocklisted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourcePort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NetworkConnectionEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.OfficeMacroAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAutoExec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMacros")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNetworkAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObfuscation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasProcessExecution")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspiciousPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("OfficeMacroResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anomalies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is64Bit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDotNet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspiciousImports")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("PeAnalysisResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeAnalysisResultId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SizeOfRawData")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeAnalysisResultId");

                    b.ToTable("PeSections");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ProcessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspicionReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.RansomwareAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("Severity");

                    b.ToTable("RansomwareAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScannedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuarantinePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuarantinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreatStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScannedFiles");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScheduledScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScheduledScans");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFileSystemAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNetworkAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObfuscation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasProcessExecution")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScriptType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("ScriptAnalysisResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.YaraMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId");

                    b.ToTable("YaraMatches");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.FileMetadataAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("FileMetadata")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.FileMetadataAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HashReputationResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("HashReputation")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.HashReputationResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.OfficeMacroAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("OfficeMacro")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.OfficeMacroAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("PeAnalysis")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeSection", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", "PeAnalysisResult")
                        .WithMany("Sections")
                        .HasForeignKey("PeAnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeAnalysisResult");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("ScriptAnalysis")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.YaraMatch", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithMany("YaraMatches")
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScannedFile", b =>
                {
                    b.Navigation("FileMetadata");

                    b.Navigation("HashReputation");

                    b.Navigation("OfficeMacro");

                    b.Navigation("PeAnalysis");

                    b.Navigation("ScriptAnalysis");

                    b.Navigation("YaraMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
