// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerSourceAntivirus.Infrastructure.Persistence;

#nullable disable

namespace PerSourceAntivirus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618225957_Phase15NetworkAndKernel")]
    partial class Phase15NetworkAndKernel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.AdsStreamInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StreamSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId");

                    b.ToTable("AdsStreamInfos");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.AmsiScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AmsiResult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasBlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScannedAtUtc");

                    b.ToTable("AmsiScanEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ArchiveEntryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArchiveScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<string>("EntryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EntrySize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanDepth")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveScannedFileId");

                    b.ToTable("ArchiveEntryResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ArpSpoofingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttackerMac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegitimateKnownMac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpoofedMac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VictimIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("ArpSpoofingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.AtomBombingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AtomContentEntropy")
                        .HasColumnType("REAL");

                    b.Property<int>("AtomContentLength")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("AtomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspiciousAtomContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("AtomBombingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ComHijackAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClsidOrPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegitimateSystemPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspiciousPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("ComHijackAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.DgaAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ConsonantVowelRatio")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("EntropyScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NxdomainStreak")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Probability")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("IsDga");

                    b.ToTable("DgaAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.DirectSyscallAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainingModulePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInSystemModule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SyscallInstructionAddress")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("DirectSyscallAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.DnsQueryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspicionReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DnsQueryEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.EmailScanResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttachmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSpoofedSender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhishingIndicators")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhishingLinkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuspiciousAttachmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousAttachmentNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId");

                    b.ToTable("EmailScanResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.EmulationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ApiCallsIntercepted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EmulatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InstructionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmulatedAtUtc");

                    b.ToTable("EmulationResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ExploitFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BaseAddress")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("ExploitFindings");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.FileMetadataAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anomalies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DocumentCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DocumentModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasEmbeddedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasJavaScript")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPolyglot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("FileMetadataResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.FilelessAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechniqueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("FilelessAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HashReputationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMalicious")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositiveDetections")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEngines")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("HashReputationResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HeapSprayAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageRegionEntropy")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuspiciousRegionCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPrivateCommittedBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("ProcessId");

                    b.ToTable("HeapSprayAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HeavensGateAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DetectedPatternAddress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWow64Process")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatternBytes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("HeavensGateAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HoneypotFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecoyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TouchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasTouched")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HoneypotFiles");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.KeyloggerDetectionAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModulePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("Severity");

                    b.ToTable("KeyloggerDetectionAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.LlmnrPoisoningAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuerierIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponderIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponderMac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpoofedIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("LlmnrPoisoningAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.LolBinAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AlertedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LolbinName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MitreTechnique")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlertedAtUtc");

                    b.HasIndex("Severity");

                    b.ToTable("LolBinAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.MbrSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DriveIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectorSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriveIndex", "IsBaseline");

                    b.ToTable("MbrSnapshots");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ModuleStompingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InMemoryHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModulePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnDiskHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TextSectionSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("ModuleStompingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.NetworkConnectionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlocklistReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocklisted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourcePort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NetworkConnectionEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.NetworkIntrusionAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PayloadLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourcePort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("Severity");

                    b.ToTable("NetworkIntrusionAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.NtdllUnhookingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MappedNtdllCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MappedPaths")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("NtdllUnhookingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.OfficeMacroAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasAutoExec")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMacros")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNetworkAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObfuscation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasProcessExecution")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspiciousPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("OfficeMacroResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PdfScanResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasEmbeddedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasJavaScript")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasLaunchAction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObjStm")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasOpenAction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRichMedia")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasXfa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaliciousObjectTypes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId");

                    b.ToTable("PdfScanResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anomalies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is64Bit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDotNet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspiciousImports")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("PeAnalysisResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeMlPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("MaliciousProbability")
                        .HasColumnType("REAL");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PredictedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Classification");

                    b.ToTable("PeMlPredictions");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeAnalysisResultId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SizeOfRawData")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeAnalysisResultId");

                    b.ToTable("PeSections");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ProcessDoppelgangingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImageExistsOnDisk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("ProcessDoppelgangingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ProcessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspicionReason")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ProcessGhostingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ImageFileAccessible")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImageFileExistsOnDisk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportedImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("ProcessGhostingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ProcessHollowingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedSequence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InjectorProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InjectorProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("Severity");

                    b.ToTable("ProcessHollowingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.RansomwareAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("Severity");

                    b.ToTable("RansomwareAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ReflectiveDllInjectionAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasPeHeader")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MemoryProtection")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RegionEntropy")
                        .HasColumnType("REAL");

                    b.Property<long>("RegionSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("SuspiciousBaseAddress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("TargetProcessId");

                    b.ToTable("ReflectiveDllInjectionAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.RootkitFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FindingType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("RootkitFindings");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.SafeFolderViolationAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttemptedOperation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasBlocked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("WasBlocked");

                    b.ToTable("SafeFolderViolationAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScannedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuarantinePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuarantinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreatStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScannedFiles");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScheduledScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScheduledScans");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFileSystemAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNetworkAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObfuscation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasProcessExecution")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScriptType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("ScriptAnalysisResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.StackPivotAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("RspValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("StackBase")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("StackLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("StackPivotAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.SteganographyAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ChannelEntropy")
                        .HasColumnType("REAL");

                    b.Property<double>("ChiSquareScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HistogramAnomalyScore")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspicionReasons")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("IsSuspicious");

                    b.ToTable("SteganographyAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.TlsInspectionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestBodySize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseBodySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc");

                    b.HasIndex("IsSuspicious");

                    b.ToTable("TlsInspectionEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.TransactedHollowingAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectionMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ModuleFileExistsOnDisk")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousModulePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("TransactedHollowingAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.UefiFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchOffset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignatureName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("UefiFindings");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.UnpackingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedPacker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPacked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnpackedFilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasUnpacked")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("UnpackingResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.WfpBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("FilterIdInboundV4")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("FilterIdOutboundV4")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress", "IsActive");

                    b.ToTable("WfpBlocks");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.WmiPersistenceAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScriptOrCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.ToTable("WmiPersistenceAlerts");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.YaraMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId");

                    b.ToTable("YaraMatches");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.AdsStreamInfo", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithMany()
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.EmailScanResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithMany()
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.FileMetadataAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("FileMetadata")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.FileMetadataAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.HashReputationResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("HashReputation")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.HashReputationResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.OfficeMacroAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("OfficeMacro")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.OfficeMacroAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PdfScanResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithMany()
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("PeAnalysis")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeSection", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", "PeAnalysisResult")
                        .WithMany("Sections")
                        .HasForeignKey("PeAnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeAnalysisResult");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("ScriptAnalysis")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.YaraMatch", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithMany("YaraMatches")
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScannedFile", b =>
                {
                    b.Navigation("FileMetadata");

                    b.Navigation("HashReputation");

                    b.Navigation("OfficeMacro");

                    b.Navigation("PeAnalysis");

                    b.Navigation("ScriptAnalysis");

                    b.Navigation("YaraMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
