// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerSourceAntivirus.Infrastructure.Persistence;

#nullable disable

namespace PerSourceAntivirus.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616201043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.NetworkConnectionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlocklistReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DestinationPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocklisted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourcePort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NetworkConnectionEvents");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Anomalies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Is64Bit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDll")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDotNet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspiciousImports")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("PeAnalysisResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PeAnalysisResultId")
                        .HasColumnType("TEXT");

                    b.Property<uint>("SizeOfRawData")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeAnalysisResultId");

                    b.ToTable("PeSections");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScannedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Entropy")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsQuarantined")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuarantinePath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("QuarantinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThreatStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScannedFiles");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFileSystemAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNetworkAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasObfuscation")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasProcessExecution")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScriptType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuspiciousPatterns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId")
                        .IsUnique();

                    b.ToTable("ScriptAnalysisResults");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.YaraMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScannedFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScannedFileId");

                    b.ToTable("YaraMatches");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("PeAnalysis")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeSection", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", "PeAnalysisResult")
                        .WithMany("Sections")
                        .HasForeignKey("PeAnalysisResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeAnalysisResult");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithOne("ScriptAnalysis")
                        .HasForeignKey("PerSourceAntivirus.Domain.Entities.ScriptAnalysisResult", "ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.YaraMatch", b =>
                {
                    b.HasOne("PerSourceAntivirus.Domain.Entities.ScannedFile", "ScannedFile")
                        .WithMany("YaraMatches")
                        .HasForeignKey("ScannedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScannedFile");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.PeAnalysisResult", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("PerSourceAntivirus.Domain.Entities.ScannedFile", b =>
                {
                    b.Navigation("PeAnalysis");

                    b.Navigation("ScriptAnalysis");

                    b.Navigation("YaraMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
